apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-config
  namespace: {{ include "common.namespace" . }}
data:
{{ (.Files.Glob "resources/config/logback.xml").AsConfig | indent 2 }}

