{{- $opensyncgw := include "opensyncgw.service" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: "{{ include "common.namespace" . }}-docker-registry-key"
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "jmxPrometheus.initContainer" . | nindent 8 }}
        - name: {{ include "common.name" . }}-readiness-opensync-gw
          image: {{ .Values.opensyncGwReadinessImage.registry }}/{{ .Values.opensyncGwReadinessImage.repository }}/{{ .Values.opensyncGwReadinessImage.tag }}
          imagePullPolicy: {{ .Values.pullPolicy | default .Values.global.pullPolicy }}
          command:
          - sh
          - -c
          - |
            apk add curl
            url=https://{{ $opensyncgw }}/ping
            counter=0
            status=$(curl --insecure --head --location --connect-timeout 5 --write-out %{http_code} --silent --output /dev/null ${url});
            while [ $counter -lt 30 ] && [ $status -ne 200 ]
            do
              echo ${url} service isnt ready. Tried $counter times
              sleep 5
              counter=`expr $counter + 1`
              status=$(curl --insecure --head --location --connect-timeout 5 --write-out %{http_code} --silent --output /dev/null ${url});
              echo Http Response code of ping request = $status
            done
            if [ $status -eq 200 ]
            then
              echo ${url} service is ready!
            else
              echo ${url} service failed to respond after 50 secs
              exit 1
            fi
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.global.testingEnabled }}
          image: {{ .Values.global.repository.registry  }}/{{ .Values.image.name }}:{{ .Values.image.tag }}-{{.Values.global.testingTimestamp}}
          {{- else }}
          image: {{ .Values.global.repository.registry  }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.pullPolicy | default .Values.global.pullPolicy }}
          env:
            {{- include "common.env" . | nindent 12 }}
            - name: PF_GATEWAY_RELEASE_URL
              value: {{ .Values.env.protocol }}://{{ .Release.Name }}-{{ .Values.env.pfGateway.service }}:{{ .Values.env.pfGateway.port }}
            - name: PF_GATEWAY_RELEASE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.fullname" . }}-creds
                  key: websocketSessionTokenEncKey
            - name: PF_GATEWAY_RELEASE_EXT_HOST
              value: {{ .Values.externallyVisible.host }}
            - name: PF_GATEWAY_RELEASE_EXT_PORT
              value: "{{ .Values.externallyVisible.port }}"
            - name: EXT_PORT_RANGE_START
              value: "{{ include "apDebugPortsStart" . }}"
            - name: EXT_PORT_RANGE_END
              value: "{{ sub (include "apDebugPortsEnd" . | atoi) 1 }}"
            - name: JVM_MEM_OPTIONS
              value: "{{ include "jmxPrometheus.jvmOpts" . }}"
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.port2 }}
              scheme: {{ .Values.probes.livenessProbe.scheme }}
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.probes.livenessProbe.successThreshold }}
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.port2 }}
              scheme: {{ .Values.probes.readinessProbe.scheme }}
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.probes.readinessProbe.successThreshold }}
          startupProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.port2 }}
              scheme: {{ .Values.probes.readinessProbe.scheme }}
            failureThreshold: {{ .Values.probes.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.probes.startupProbe.periodSeconds}}
          {{- end }}
          volumeMounts:
          - mountPath: /opt/tip-wlan/certs/client_keystore.jks
            name: certificates
            subPath: client_keystore.jks
          - mountPath: /opt/tip-wlan/certs/truststore.jks
            name: certificates
            subPath: truststore.jks
          - mountPath: /opt/tip-wlan/certs/server.pkcs12
            name: certificates
            subPath: server.pkcs12
          - mountPath: /app/port-forwarding-gateway/logback.xml
            name: configuration
            subPath: logback.xml
          {{- include "jmxPrometheus.configVolumeMount" . | nindent 10 }}
          {{- include "jmxPrometheus.tmpVolumeMount" . | nindent 10 }}

          ports:
            - name: {{ .Values.service.name1 }}
              containerPort: {{ .Values.service.port1 }}
              protocol: TCP
            - name: {{ .Values.service.name2 }}
              containerPort: {{ .Values.service.port2 }}
              protocol: TCP
            {{- if .Values.debug.enabled }}
            - name: {{ .Values.service.name3 }}
              containerPort: {{ .Values.service.port3 }}
              protocol: TCP
            {{- end }}
            {{- include "container.dev.apDebugPorts" . | nindent 10 }}
            {{- include "jmxPrometheus.port" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: certificates
        secret:
          secretName: tip-common-kafka-client-certs
          defaultMode: 0400
      - name: configuration
        configMap:
            name: {{ include "common.fullname" . }}-config
            defaultMode: 0755
      {{- include "jmxPrometheus.configVolume" . | nindent 6 }}
      {{- include "jmxPrometheus.tmpVolume" . | nindent 6 }}