apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-creds
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ template "common.name" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  websocketSessionTokenEncKey: {{ .Values.creds.websocketSessionTokenEncKey | b64enc | quote }}