apiVersion: v2
name: tip-wlan
description: Telecom Infra Platform - Wifi
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0

home: https://telecominfraproject.com/wifi/
sources:
- https://github.com/Telecominfraproject
icon: 

# todo move these to helmfile
dependencies:
- name: opensync-gw-static
  version: 0.1.0
  condition: opensync-gw-static.enabled
- name: opensync-gw-cloud
  version: 0.1.0
  condition: opensync-gw-cloud.enabled
- name: opensync-mqtt-broker
  version: 0.1.0
  condition: opensync-mqtt-broker.enabled
- name: wlan-cloud-graphql-gw
  version: 0.1.0
  condition: wlan-cloud-graphql-gw.enabled
- name: wlan-cloud-static-portal
  version: 0.1.0
  condition: wlan-cloud-static-portal.enabled
## IntegratedCloudComponent should be disabled for distributed deployment
- name: wlan-integrated-cloud-component-service
  version: 0.1.0
  condition: wlan-integrated-cloud-component-service.enabled
- name: wlan-portal-service
  version: 0.1.0
  condition: wlan-portal-service.enabled
- name: wlan-prov-service
  version: 0.1.0
  condition: wlan-prov-service.enabled
- name: wlan-ssc-service
  version: 0.1.0
  condition: wlan-ssc-service.enabled
- name: wlan-spc-service
  version: 0.1.0
  condition: wlan-spc-service.enabled
- name: wlan-port-forwarding-gateway-service
  version: 0.1.0
  condition: wlan-port-forwarding-gateway-service.enabled
- name: common
  version: 0.1.0