apiVersion: v2
name: tip-wlan
description: Telecom Infra Platform - Wifi

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0

home: https://telecominfraproject.com/wifi/
sources:
- https://github.com/Telecominfraproject
icon: 

dependencies:
  - name: opensync-gw-static
    version: 0.1.0
    condition: opensync-gw-static.enabled
  - name: opensync-mqtt-broker
    version: 0.1.0
    condition: opensync-mqtt-broker.enabled
  - name: nginx-ingress
    version: 0.1.0
    condition: nginx-ingress-controller.enabled
  - name: common
    version: 0.1.0
  - name: zookeeper
    version: 0.1.0
    condition: zookeeper.enabled
  - name: kafka
    version: 0.1.0
    condition: kafka.enabled