apiVersion: v2
name: tip-wlan
description: Telecom Infra Platform - Wifi

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0

home: https://telecominfraproject.com/wifi/
sources:
- https://github.com/Telecominfraproject
icon: 

dependencies:
- name: opensync-gw-static
  version: 0.1.0
  condition: opensync-gw-static.enabled
- name: opensync-gw-cloud
  version: 0.1.0
  condition: opensync-gw-cloud.enabled
- name: opensync-mqtt-broker
  version: 0.1.0
  condition: opensync-mqtt-broker.enabled
- name: wlan-cloud-graphql-gw
  version: 0.1.0
  condition: wlan-cloud-graphql-gw.enabled
- name: wlan-cloud-static-portal
  version: 0.1.0
  condition: wlan-cloud-static-portal.enabled
## IntegratedCloudComponent should be disabled for distributed deployment
- name: wlan-integrated-cloud-component-service
  version: 0.1.0
  condition: wlan-integrated-cloud-component-service.enabled
- name: wlan-portal-service
  version: 0.1.0
  condition: wlan-portal-service.enabled
- name: wlan-prov-service
  version: 0.1.0
  condition: wlan-prov-service.enabled
- name: wlan-ssc-service
  version: 0.1.0
  condition: wlan-ssc-service.enabled
- name: wlan-spc-service
  version: 0.1.0
  condition: wlan-spc-service.enabled
- name: wlan-port-forwarding-gateway-service
  version: 0.1.0
  condition: wlan-port-forwarding-gateway-service.enabled
- name: nginx-ingress-controller
  version: 0.1.0
  condition: nginx-ingress-controller.enabled
- name: common
  version: 0.1.0

- name: kafka
  version: 12.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: kafka.enabled
- name: postgresql
  version: 10.1.0
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: cassandra
  version: 7.0.1
  repository: https://charts.bitnami.com/bitnami
  condition: cassandra.enabled
