apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster2
 annotations:
   volume.beta.kubernetes.io/storage-class: glusterfs-storage
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi