bases:
- helmfile-environment.yaml
- helmfile-defaults.yaml
---

releases:
- name: postgres-{{ .Environment.Values.global.namespace }}
  namespace: {{ .Environment.Values.global.namespace }}
  chart: bitnami/postgresql
  version: 9.8.4
  condition: postgres.enabled
  labels:
    role: prerequisites
    app: postgres
  values:
  - postgresqlDatabase: tip
    image:
      tag: 11.8.0-debian-10-r58
      debug: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: {{ .Environment.Values.global.monitoring.namespace }}
        additionalLabels:
          release: prometheus-operator
    postgresqlUsername: {{ .Environment.Values.postgres.user }}
    postgresqlPassword: {{ .Environment.Values.postgres.password }}
    pgHbaConfiguration: |
      hostssl replication repl_user 0.0.0.0/0 md5 clientcert=0
      hostssl postgres postgres 0.0.0.0/0 cert clientcert=1
      hostssl postgres postgres ::/0 cert clientcert=1
      hostssl all all 0.0.0.0/0 md5 clientcert=1
    replication:
      enabled: true
      user: {{ .Environment.Values.postgres.replication.user }}
      password: {{ .Environment.Values.postgres.replication.password }}
      slaveReplicas: 1
    persistence:
      enabled: true
      storageClass: {{ .Environment.Values.storageClass }}
    volumePermissions:
      enabled: true
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    tls:
      enabled: true
      certificatesSecret: tip-{{ .Environment.Values.global.namespace }}-common-postgres-certs
      certFilename: cert.crt
      certKeyFilename: cert.key
      certCAFilename: cacert.pem
    initdbScriptsConfigMap: tip-{{ .Environment.Values.global.namespace }}-common-postgres-scripts
    extraEnv:
    - name: PGSSLCERT
      value: /opt/tip-wlan/certs/postgresclientcert.pem
    - name: PGSSLKEY
      value: /opt/tip-wlan/certs/postgresclientkey_dec.pem
    - name: PGSSLROOTCERT
      value: "/opt/tip-wlan/certs/cacert.pem"
    slave:
      extraVolumes:
  jsonPatches:
  - target:
      version: v1
      group: apps
      kind: StatefulSet
      name: postgres-{{ .Environment.Values.global.namespace }}-postgresql-master
    patch:
    - op: replace
      path: /spec/template/spec/initContainers/0/command
      value:
      - /bin/sh
      - -cx
      - |
        chown 1001:1001 /bitnami/postgresql
        mkdir -p /bitnami/postgresql/data /bitnami/postgresql/conf
        chmod 700 /bitnami/postgresql/data /bitnami/postgresql/conf
        find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R 1001:1001
        chmod -R 777 /dev/shm
        cp /tmp/certs/* /opt/bitnami/postgresql/certs/
        chown -R 1001:1001 /opt/bitnami/postgresql/certs/
        chmod 600 /opt/bitnami/postgresql/certs/cert.key
        chmod 600 /opt/bitnami/postgresql/certs/postgresclientkey_dec.pem

- name: zookeeper-{{ .Environment.Values.global.namespace }}
  namespace: {{ .Environment.Values.global.namespace }}
  chart: incubator/zookeeper
  version: 2.1.4
  condition: zookeeper.enabled
  labels:
    role: prerequisites
    app: zookeeper
  values:
  - persistence:
      enabled: true
      storageClass: {{ .Environment.Values.storageClass }}
    replicaCount: 1

- name: kafka-{{ .Environment.Values.global.namespace }}
  namespace: {{ .Environment.Values.global.namespace }}
  chart: bitnami/kafka
  version: 11.8.7
  condition: kafka.enabled
  labels:
    role: prerequisites
    app: kafka
  values:
  - replicaCount: 1
    image:
      debug: true
    auth:
      clientProtocol: mtls
      interBrokerProtocol: plaintext
      jksSecret: tip-{{ .Environment.Values.global.namespace }}-common-kafka-certs
      jksPassword: {{ .Environment.Values.credentials.keyPassword }}
      tlsEndpointIdentificationAlgorithm: https
      jaas:
        clientUsers:
        - brokerUser
        clientPassword:
        - brokerPassword
    # existingConfigmap: tip-{{ .Environment.Values.global.namespace }}-common-kafka-config
    # allowPlaintextListener: true
    persistence:
      enabled: true
      storageClass: {{ .Environment.Values.storageClass }}
    metrics:
      serviceMonitor:
        enabled: false
        namespace: {{ .Environment.Values.global.monitoring.namespace }}
        selector:
          release: prometheus-operator
    zookeeper:
      enabled: false
    externalZookeeper:
      servers:
      - zookeeper-{{ .Environment.Values.global.namespace }}

- name: cassandra-{{ .Environment.Values.global.namespace }}
  namespace: {{ .Environment.Values.global.namespace }}
  chart: bitnami/cassandra
  version: 6.0.1
  condition: cassandra.enabled
  labels:
    role: prerequisites
    app: cassandra
  values:
  - tlsEncryptionSecretName: tip-{{ .Environment.Values.global.namespace }}-common-cassandra-certs
  - image:
      debug: true
  - persistence:
      enabled: true
      storageClass: {{ .Environment.Values.storageClass }}
  - replicaCount: 3
  - cluster:
      name: TipWlanCluster
      seedCount: 1
      internodeEncryption: all
      clientEncryption: true
  - exporter:
      enabled: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-operator
  - dbUser:
      user: {{ .Environment.Values.cassandra.user }}
      password: {{ .Environment.Values.cassandra.password }}
  - resources:
      limits: {}
      requests:
        cpu: 1
        memory: 3Gi

- name: tip-{{ .Environment.Values.global.namespace }}-credentials
  namespace: {{ .Environment.Values.global.namespace }}
  chart: credentials
  labels:
    role: prerequisites
    app: credentials
  values:
  - ssl:
      keyPassword: {{ .Environment.Values.credentials.keyPassword }}
      keystorePassword: {{ .Environment.Values.credentials.keystorePassword }}
      truststorePassword: {{ .Environment.Values.credentials.truststorePassword }}
    db:
      postgresUser:
        password: {{ .Environment.Values.postgres.password }}
      tipUser:
        password: {{ .Environment.Values.postgres.password }}
    schema_repo:
      username: {{ .Environment.Values.credentials.jFrog.user }}
      password: {{ .Environment.Values.credentials.jFrog.password }}
    cassandra:
      tip_user: {{ .Environment.Values.cassandra.user }}
      tip_password: {{ .Environment.Values.cassandra.password }}
    websocketSessionTokenEncKey: {{ .Environment.Values.credentials.websocketSessionTokenEncKey }}
    dockerRegistrySecret: {{ .Environment.Values.credentials.dockerSecret }}

- name: tip-{{ .Environment.Values.global.namespace }}-efs-provisioner
  namespace: {{ .Environment.Values.global.namespace }}
  chart: stable/efs-provisioner
  version: 0.13.0
  condition: efs-provisioner.enabled
  labels:
    role: prerequisites
    app: efs-provisioner
  values:
  - serviceAccount:
      create: true
      name: efs-provisioner
  - provisioner:
      nameExtension: efs-provisioner
      replicaCount: 1
      strategyType: Recreate
      image:
        name: quay.io/external_storage/efs-provisioner
        tag: latest
      efsFileSystemId: fs-8a3fa867
      awsRegion: ca-central-1
      dnsName: ""
      provisionerName: shared-provisioner
      efsDnsName: fs-8a3fa867.efs.ca-central-1.amazonaws.com
      storageClass: aws-efs