#################################################################
# Credentials and secrets for reuse in other charts
#################################################################

creds:
  ssl:
    keyPassword: mypassword
    keystorePassword: mypassword
    truststorePassword: mypassword
  db:
    postgresUser:
      password: DUMMY_POSTGRES_PASSWORD
    tipUser:
      password: tip_password
  schema_repo:
    username: tip-read
    password: tip-read
  cassandra:
    tip_user: tip_user
    tip_password: tip_password