apiVersion: v2
name: wlan-cloud-graphql-gw
description: WLAN Cloud Apollo Server Helm Chart

type: application
version: 0.1.0
appVersion: 0.0.1

dependencies:
- name: common
  version: 0.1.0
  repository: file://../common