apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ tpl (.Files.Glob "resources/config/certs/*").AsSecrets . | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "common.name" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.creds.enabled }}
  sslKeyPassword: {{ .Values.creds.sslKeyPassword | b64enc | quote }}
  sslKeystorePassword: {{ .Values.creds.sslKeystorePassword | b64enc | quote }}
  sslTruststorePassword: {{ .Values.creds.sslTruststorePassword | b64enc | quote }}
  {{- end }}