apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-creds
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ template "common.name" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  sslKeyPassword: {{ .Values.global.certificatePasswords.sslKey | b64enc | quote }}
  sslKeystorePassword: {{ .Values.global.certificatePasswords.sslKeystore | b64enc | quote }}
  sslTruststorePassword: {{ .Values.global.certificatePasswords.sslTruststore | b64enc | quote }}
