apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-clientconfig
  namespace: {{ include "common.namespace" . }}
data:
  admin-client.properties: |
    ssl.endpoint.identification.algorithm=
    security.protocol=SSL
    ssl.key.password={{ .Values.creds.sslKeyPassword | b64enc }}
    ssl.keystore.location=/etc/kafka/secrets/kafka-server.pkcs12
    ssl.keystore.password={{ .Values.creds.sslKeystorePassword | b64enc }}
    ssl.keystore.type=PKCS12
    ssl.truststore.location=/etc/kafka/secrets/truststore.jks
    ssl.truststore.password={{ .Values.creds.sslTruststorePassword | b64enc }}
    ssl.truststore.type=JKS
    bootstrap.servers={{ include "kafka.service" . }}:9093
