---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-certs
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ template "common.name" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  truststore_creds: {{ .Values.creds.sslTruststorePassword | b64enc }}
  keystore_creds: {{ .Values.creds.sslKeystorePassword | b64enc }}
  key_creds: {{ .Values.creds.sslKeyPassword | b64enc }}
  truststore.jks: {{ .Files.Get "resources/config/certs/truststore.jks" | b64enc }}
  kafka-server.pkcs12: {{ .Files.Get "resources/config/certs/kafka-server.pkcs12" | b64enc }}
  README: {{ .Files.Get "resources/config/certs/README.md" | b64enc }}
