apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
  {{- include "kafka.broker.labels" . | nindent 4 }}
spec:
  ports:
  - name: broker
    port: {{ .Values.headless.sslPort }}
    targetPort: kafka
  selector:
  {{- include "kafka.broker.matchLabels" . | nindent 4 }}
