{{- if .Values.global.integratedDeployment }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: {{ .Values.service.port1 }}
      protocol: TCP
      name: {{ .Values.service.name1 }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.global.nodePortPrefix | default .Values.nodePortPrefix }}{{ .Values.service.nodePort1 }}
      {{- end }}
    - port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.port2 }}
      protocol: TCP
      name: {{ .Values.service.name2 }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.global.nodePortPrefix | default .Values.nodePortPrefix }}{{ .Values.service.nodePort2 }}
      {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}
