---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opensync-gw-cloud-depends-on-role
  namespace: {{ include "common.namespace" . }}
rules:
- apiGroups: ["batch", "apps", ""]
  resources: ["pods", "services", "jobs"]
  verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opensync-gw-cloud-depends-on-role-binding
  namespace: {{ include "common.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "common.serviceAccountName" . }}
roleRef:
  kind: Role
  name: opensync-gw-cloud-depends-on-role
  apiGroup: rbac.authorization.k8s.io
