apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: {{ .Values.service.port1 }}
      protocol: TCP
      name: {{ .Values.service.name1 }}
      nodePort: {{ .Values.global.nodePortPrefix }}{{ .Values.service.nodePort1 }}
    - port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.port2 }}
      protocol: TCP
      name: {{ .Values.service.name2 }}
      nodePort: {{ .Values.global.nodePortPrefix }}{{ .Values.service.nodePort2 }}
    - port: {{ .Values.service.port3 }}
      targetPort: {{ .Values.service.port3 }}
      protocol: TCP
      name: {{ .Values.service.name3 }}
      nodePort: {{ .Values.global.nodePortPrefix }}{{ .Values.service.nodePort3 }}
    - port: {{ .Values.service.port4 }}
      targetPort: {{ .Values.service.port4 }}
      protocol: TCP
      name: {{ .Values.service.name4 }}
      nodePort: {{ .Values.global.nodePortPrefix }}{{ .Values.service.nodePort4 }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
