apiVersion: v1
kind: Secret
metadata:
  name: opensync-common-certs
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
{{ tpl (.Files.Glob "resources/config/certs/*").AsSecrets . | indent 2 }}