{{ if not .Values.controller.defaultTLS.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-ingress.defaultTLSName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.controller.defaultTLS.cert }}
  tls.key: {{ .Values.controller.defaultTLS.key }}
{{- end }}
