---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tip-{{ .Release.Namespace }}-common-kafka-config
  namespace: {{ .Release.Namespace }}
data:
{{ tpl (.Files.Glob "resources/config/server.properties").AsConfig . | indent 2 }}