apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-log-config
  namespace: {{ include "common.namespace" . }}
data:
{{ (.Files.Glob "resources/config/logback.xml").AsConfig | indent 2 }}
  datasource.properties: |-
    singleDataSource.url=jdbc:postgresql://{{- include "postgresql.service" . -}}:5432/prov_db
    singleDataSource.username={{ .Values.global.postgres.singleDataSource.username }}
    singleDataSource.password={{ .Values.global.postgres.singleDataSource.password }}
    singleDataSource.driverClass=org.postgresql.Driver
    singleDataSource.ssl=true
    singleDataSource.sslmode=verify-ca
    singleDataSource.sslcert=/opt/tip-wlan/certs/postgresclientcert.pem
    singleDataSource.sslfactory=org.postgresql.ssl.LibPQFactory
    singleDataSource.sslkey=/opt/tip-wlan/certs/postgresclient.p12
    singleDataSource.sslrootcert=/opt/tip-wlan/certs/cacert.pem
    singleDataSource.sslkeypassword={{ .Values.global.certificatePasswords.sslKey }}
