apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-log-config
  namespace: {{ include "common.namespace" . }}
data:
  datasource.properties:
    singleDataSource.url=jdbc:postgresql://tip-wlan-postgresql:5432/prov_db
    singleDataSource.username={{ .Values.creds.postgres.singleDataSourceUsername }}
    singleDataSource.password={{ .Values.creds.postgres.singleDataSourcePassword }}
    singleDataSource.driverClass=org.postgresql.Driver
    singleDataSource.ssl=true
    singleDataSource.sslmode=verify-ca
    singleDataSource.sslcert=/opt/tip-wlan/certs/postgresclientcert.pem
    singleDataSource.sslfactory=org.postgresql.ssl.LibPQFactory
    singleDataSource.sslkey=/opt/tip-wlan/certs/postgresclient.p12
    singleDataSource.sslrootcert=/opt/tip-wlan/certs/cacert.pem
    singleDataSource.sslkeypassword=mypassword
{{ tpl (.Files.Glob "resources/config/*").AsConfig . | indent 2 }}
