apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-log-config
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/logback.xml").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-cassandra-cql
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/cqlshrc.tip-wlan").AsConfig . | indent 2 }}
