apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-ssc-config
  namespace: {{ include "common.namespace" . }}
data:
{{ (.Files.Glob "resources/config/logback.xml").AsConfig | indent 2 }}
  cassandra-application.conf: >-
    datastax-java-driver {
        basic {
            contact-points = [ "{{ include "cassandra.service" . }}:9042" ]
            load-balancing-policy.local-datacenter = datacenter1
            session-keyspace = tip_wlan_keyspace
        }

        advanced.ssl-engine-factory {
            class = DefaultSslEngineFactory
            hostname-validation = false
            truststore-path = /opt/tip-wlan/certs/truststore.jks
            truststore-password = {{ .Values.global.certificatePasswords.sslTruststore }}
            keystore-path = /opt/tip-wlan/certs/cassandra_server_keystore.jks
            keystore-password = {{ .Values.global.certificatePasswords.sslKeystore }}
        }

        advanced.auth-provider {
            class = PlainTextAuthProvider
            username = {{ .Values.global.cassandra.username }}
            password = {{ .Values.global.cassandra.password }}
        }
    }

  cqlshrc.tip-wlan: |
  {{ tpl (.Files.Get "files/cqlshrc.tip-wlan") . | nindent 4 }}
