#################################################################
# Global configuration default values that can be inherited by
# all subcharts.
#################################################################
