{{- if .Values.disableTLSv13.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-ssl-config
  namespace: {{ include "common.namespace" . }}
type: Opaque
data:
  ssl.properties: {{ tpl ( .Files.Get "resources/config/ssl.properties" ) . | b64enc }}
{{- end }}