apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: {{ .Values.service.port1 }}
      protocol: TCP
      name: {{ .Values.service.name1 }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.global.nodePortPrefixExt | default .Values.nodePortPrefixExt }}{{ .Values.service.nodePort1 }}
      {{- end }}
    - port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.port2 }}
      protocol: TCP
      name: {{ .Values.service.name2 }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.global.nodePortPrefixExt | default .Values.nodePortPrefixExt }}{{ .Values.service.nodePort2 }}
      {{- end }}
    {{- if .Values.debug.enabled }}
    - port: {{ .Values.service.port3 }}
      targetPort: {{ .Values.service.port3 }}
      protocol: TCP
      name: {{ .Values.service.name3 }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.global.nodePortPrefixExt | default .Values.nodePortPrefixExt }}{{ .Values.service.nodePort3 }}
      {{- end }}
    {{- end }}      
    {{- include "service.dev.debugport" . | nindent 2 }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
