apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-headless
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ template "common.name" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "postgresql.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: {{ template "postgresql.port" . }}
      targetPort: tcp-postgresql
  selector:
    app: {{ template "common.name" . }}
    release: {{ .Release.Name | quote }}
