apiVersion: v2
name: wlan-integrated-cloud-component-service
description: WLAN 'Integrated cloud component' (combines Portal, Prov and SSC) Service Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: 0.0.1

dependencies:
- name: common
  version: 0.1.0
  repository: file://../common
