apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ tpl (.Files.Glob "resources/config/certs/*").AsSecrets . | indent 2 }}