---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tip-{{ .Release.Namespace }}-common-kafka-config
  namespace: {{ .Release.Namespace }}
data:
{{ tpl (.Files.Glob "resources/config/server.properties").AsConfig . | indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tip-{{ .Release.Namespace }}-common-postgres-scripts
  namespace: {{ .Release.Namespace }}
data:
{{ tpl (.Files.Glob "resources/scripts/creation-replication-user-role.sh").AsConfig . | indent 2 }}
