{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaimData) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.fullname" . }}-data
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ include "common.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
{{- if .Values.persistence.volumeNameData }}   
  volumeName: .Values.persistence.volumeNameData
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.sizeData }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}