apiVersion: v1
kind: Secret
metadata:
  name: opensync-mqtt-broker-certs
  namespace: {{ include "common.namespace" . }}
type: Opaque
data:
{{ tpl (.Files.Glob "resources/config/certs/*").AsSecrets . | indent 2 }}