apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configurations-override
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/cqlshrc.tip-wlan").AsConfig . | indent 2 }}
