apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configurations-override
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/*").AsConfig . | indent 2 }}
