{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "networkPolicy.apiVersion" . }}
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "common.selectorLabels" . | nindent 6 }}
  ingress:
    # Allow inbound connections
    # CQL and Thrift ports
    - ports:
        - port: {{ .Values.service.port }}
        - port: {{ .Values.service.thriftPort }}
      from:
      {{- if not .Values.networkPolicy.allowExternal }}
        - podSelector:
            matchLabels:
              {{ include "common.fullname" . }}-client: "true"
      {{- end }}
        - podSelector:
            matchLabels: {{- include "common.selectorLabels" . | nindent 14 }}
    # Internal ports
    - ports:
        - port: intra
        - port: tls
        - port: jmx
      from:
        - podSelector:
            matchLabels: {{- include "common.selectorLabels" . | nindent 14 }}
    {{- if .Values.metrics.enabled }}
    # Allow prometheus scrapes for metrics
    - ports:
        - port: 8080
    {{- end }}
{{- end }}
