{{- if (not .Values.dbUser.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.dbUser.password }}
  cassandra-password: {{ .Values.dbUser.password | b64enc | quote }}
  {{- else if (not .Values.dbUser.forcePassword) }}
  cassandra-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  cassandra-password: {{ required "A Cassandra Password is required!" .Values.dbUser.password }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-ssl-certs
  namespace: {{ include "common.namespace" . }}
type: Opaque
data:
  truststore: {{ .Files.Get "resources/config/certs/truststore.jks" | b64enc }}
  truststore-password: {{ .Values.creds.sslTruststorePassword | b64enc }}
  keystore: {{ .Files.Get "resources/config/certs/cassandra_server_keystore.jks" | b64enc }}
  keystore-password: {{ .Values.creds.sslKeystorePassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-client-certs
  namespace: {{ include "common.namespace" . }}
type: Opaque
data:
{{ tpl (.Files.Glob "resources/config/certs/*").AsSecrets . | indent 2 }}
  keystore_creds: {{ .Values.creds.sslKeystorePassword | b64enc }}
  truststore_creds: {{ .Values.creds.sslTruststorePassword | b64enc }}
