{{- if and .Release.Namespace (.Values.createReleaseNamespace | default false) -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "common.namespace" . }}
  labels:
    release: {{ .Release.Name }}
{{- end -}}