shared:
  scalability: &jvm-options
    tip_wlan_ovsdb_listener_threadPoolSize: 50
    tip_wlan_AsyncExecutor_CorePoolSize: 10
    tip_wlan_AsyncExecutor_MaxPoolSize: 50
    tip_wlan_AsyncExecutor_QueueCapacity: 50
    tip_wlan_httpClientConfig_maxConnectionsTotal: 100
    tip_wlan_httpClientConfig_maxConnectionsPerRoute: 10
    tip_wlan_maxHttpThreads:  100
    JVM_MEM_OPTIONS: " "
    singleDataSource_maxTotalConnections: 8
    singleDataSource_maxIdleConnections: 8
    singleDataSource_maxPreparedStatements: 200
    singleDataSource_maxIdlePreparedStatements: 200
    singleDataSource_maxTotalConnections: 8
    singleDataSource_maxIdleConnections: 8
    singleDataSource_maxPreparedStatements: 200
    singleDataSource_maxIdlePreparedStatements: 200

global:
  nodePortPrefix: 302
  nodePortPrefixExt: 304

  pullPolicy: Always

  integratedDeployment: false
  testingEnabled: false
  testingTimestamp:

  certificatePasswords:
    sslKey: &sslKeyPassword "mypassword"
    sslKeystore: &sslKeystorePassword "mypassword"
    sslTruststore: &sslTruststorePassword "mypassword"
  cassandra:
    username: tip_user
    password: tip_password
  postgres:
    password: postgres
    singleDataSource:
      username: tip_user
      password: tip_password
  tip:
    password: tip_password
  schema:
    username: tip-read
    password: tip-read

dockerRegistrySecret: ewoJImF1dGhzIjogewoJCSJ0aXAtdGlwLXdsYW4tY2xvdWQtZG9ja2VyLXJlcG8uamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImRHbHdMWEpsWVdRNmRHbHdMWEpsWVdRPSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuOCAobGludXgpIgoJfQp9
annotations: {
    "helm.sh/resource-policy": keep
}

opensync-gw-static:
  enabled: false

opensync-gw-cloud:
  enabled: true
  externalhost:
    address:
      ovsdb: tip-wlan-opensync-gw-cloud
      mqtt: tip-wlan-opensync-mqtt-broker
  persistence:
    enabled: true
  filestore:
    url: "https://tip-wlan-opensync-gw-cloud:9096"
  scalability:
    <<: *jvm-options

opensync-mqtt-broker:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: glusterfs-storage

wlan-cloud-graphql-gw:
  enabled: true
  env:
    portalsvc: tip-wlan-wlan-portal-service:9051
  ingress:
    hosts:
      - host: wlan-ui-graphql.wlan.local
        paths: [
           /
          ]
    tls:
    - hosts:
      - wlan-ui-graphql.wlan.local
      secretName: nginx-ingress-controller-default-server-secret

wlan-cloud-static-portal:
  enabled: true
  env:
    graphql: https://wlan-ui-graphql.wlan.local
  service:
    type: NodePort
  ingress:
    hosts:
      - host: wlan-ui.wlan.local
        paths: [
           /
          ]
    tls:
    - hosts:
      - wlan-ui.wlan.local
      secretName: nginx-ingress-controller-default-server-secret

wlan-portal-service:
  enabled: true
  persistence:
    enabled: true
    storageClass: glusterfs-storage
    filestoreSize: 1Gi
  scalability:
    <<: *jvm-options

wlan-prov-service:
  enabled: true
  scalability:
    <<: *jvm-options

wlan-ssc-service:
  enabled: true
  scalability:
    <<: *jvm-options

wlan-spc-service:
  enabled: true
  scalability:
    <<: *jvm-options

wlan-port-forwarding-gateway-service:
  enabled: true
  creds:
    websocketSessionTokenEncKey: MyToKeN0MyToKeN1
  externallyVisible:
    host: api.wlan.demo.lab.wlan.tip.build
    port: 30401

nginx-ingress-controller:
  enabled: true
  controller:
    nodeSelector: {
      type: master
    }
    config:
      externalStatusAddress: "192.168.56.101"

kafka:
  enabled: true
  persistence:
    enabled: true
    storageClass: glusterfs-storage
  creds:
    sslKeyPassword: *sslKeyPassword
    sslKeystorePassword: *sslKeystorePassword
    sslTruststorePassword: *sslTruststorePassword
  auth:
    jksPassword: *sslKeystorePassword

cassandra:
  enabled: true
  persistence:
    enabled: true
    storageClass: glusterfs-storage

postgresql:
  enabled: true
  persistence:
    enabled: true
    storageClass: glusterfs-storage
