# This is a development override file.
# It overrides the default Tip-Wlan parent chart behaviour
#
# It can be tweaked, based on the need to support different
# dev environments.
# This file expects to have a GlusterFS storage solution running
# before "helm install" is performed. 
#################################################################
# Global configuration overrides.
#
# These overrides will affect all helm charts (ie. applications)
# that are listed below and are 'enabled'.
#################################################################
global:
  # Change to an unused port prefix range to prevent port conflicts
  # with other instances running within the same k8s cluster
  nodePortPrefix: 302
  nsPrefix: connectus
  # image pull policy
  pullPolicy: Always

  repository: docker-repo.lab.connectus.ai:5000
  # override default mount path root directory
  # referenced by persistent volumes and log files
  persistence:

  # flag to enable debugging - application support required
  debugEnabled: true

annotations: {
    "helm.sh/resource-policy": keep
}
#################################################################
# Enable/disable and configure helm charts (ie. applications)
# to customize the TIP-WLAN deployment.
#################################################################
opensync-gw-static:
  enabled: true
opensync-mqtt-broker:
  enabled: true
  persistence:
    enabled: true
    annotations: {
      volume.beta.kubernetes.io/storage-class: glusterfs-storage,
      "helm.sh/resource-policy": keep
    }
nginx-ingress-controller:
  enabled: true