#################################################################
# Global configuration overrides.
#
# These overrides will affect all helm charts (ie. applications)
# that are listed below and are 'enabled'.
#################################################################
global:
  # Change to an unused port prefix range to prevent port conflicts
  # with other instances running within the same k8s cluster
  nodePortPrefix: 302
  nsPrefix: rahul
  # image pull policy
  pullPolicy: IfNotPresent

  repository: docker-repo.lab.connectus.ai:5000
  repositoryCred:
    user: connectus_docker
    password: myconnectus
  # override default mount path root directory
  # referenced by persistent volumes and log files
  persistence:

  # flag to enable debugging - application support required
  debugEnabled: true

#################################################################
# Enable/disable and configure helm charts (ie. applications)
# to customize the TIP-WLAN deployment.
#################################################################
opensync-gw-static:
  enabled: true
opensync-mqtt-broker:
  enabled: true
nginx-ingress-controller:
  enabled: true  