name: Helm validation

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GH_AUTOMATION_KEY }}
          submodules: true
      - name: Validators setup
        working-directory: /tmp
        env:
          KUBESCORE_VERSON: 1.7.1
        run: |
          mkdir /tmp/k8s-validators

          curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          rm -f kubeval-linux-amd64.tar.gz

          curl -LO https://github.com/zegl/kube-score/releases/download/v${{ env.KUBESCORE_VERSON }}/kube-score_${{ env.KUBESCORE_VERSON }}_linux_amd64.tar.gz
          tar xf kube-score_${{ env.KUBESCORE_VERSON }}_linux_amd64.tar.gz
          rm -f kube-score_${{ env.KUBESCORE_VERSON }}_linux_amd64.tar.gz

          curl -LO https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz
          tar xf helm-v3.2.4-linux-amd64.tar.gz
          mv linux-amd64/helm .
          rm -fr helm-v3.2.4-linux-amd64.tar.gz linux-amd64

          echo "::add-path::/tmp/k8s-validators/"
      - name: Cache validators
        uses: actions/cache@v1
        with:
          path: /tmp/k8s-validators
          key: ${{ runner.os }}-k8s-validators
      - name: Test tip-wlan
        working-directory: tip-wlan
        run: |
          echo "Kubeval test"
          helm template -f values-test.yaml . | kubeval --ignore-missing-schemas

          echo "Kube-score test"
          helm template -f values-test.yaml . | kube-score score -
      - name: Test glusterfs
        working-directory: glusterfs/kube-templates
        run: |
          echo "Kubeval test"
          kubeval *.yaml

          echo "Kube-score test"
          kube-score score *.yaml