name: Helm CI - TIP WLAN Cloud Master

on: 
  push:
    branches: [ master ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to TIP Helm chart registry
        run: helm repo add tip-wlan-cloud-helm-virtual-repo https://tip.jfrog.io/artifactory/tip-wlan-cloud-helm-virtual-repo --username build-pipeline --password ${{ secrets.HELM_REPO_PASSWORD }}
      - name: Build tip-wlan chart file
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            PACKAGE_OPTS="--version ${GITHUB_REF#refs/tags/v}"
          else
            PACKAGE_OPTS=""
          fi
          helm package $PACKAGE_OPTS -u tip-wlan
      - name: Store chart as artifact
        uses: actions/upload-artifact@v2
        with:
          name: helm-chart
          path: tip-wlan-*.tgz
      - name: Upload tip-wlan chart to the TIP helm registry
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            curl -ubuild-pipeline:${{ secrets.HELM_REPO_PASSWORD }} -T tip-wlan-${GITHUB_REF#refs/tags/v}.tgz "https://tip.jfrog.io/artifactory/tip-wlan-cloud-helm-repo/tip-wlan-${GITHUB_REF#refs/tags/v}.tgz"
          else
            curl -ubuild-pipeline:${{ secrets.HELM_REPO_PASSWORD }} -T tip-wlan-*.tgz "https://tip.jfrog.io/artifactory/tip-wlan-cloud-helm-repo/tip-wlan-master.tgz"
          fi

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: create RELEASE.md
        run: |
          cat << EOF > RELEASE.md
          ## Installation

          \`\`\`
          $ helm repo add tip-wlan-cloud-helm-virtual-repo https://tip.jfrog.io/artifactory/tip-wlan-cloud-helm-virtual-repo --username <USERNAME> --password <PASSWORD>
          $ helm install tip-wlan-cloud-helm-virtual-repo/tip-wlan --version ${GITHUB_REF#refs/tags/v}
          \`\`\`

          EOF
      - name: install keepachangelog
        run: pip install keepachangelog
      - name: get changelog entry
        continue-on-error: true
        run: python .github/workflows/extract-changelog-entry.py ${GITHUB_REF#refs/tags/v} >> RELEASE.md
      - name: download Helm chart artifact
        uses: actions/download-artifact@v2
        with:
          name: helm-chart
      - name: create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: tip-wlan-*.tgz
          body_path: RELEASE.md
          prerelease: ${{ contains(github.ref, 'rc') }}
